//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.appassit.adapter;

import android.content.Context;

public final class CityAdapter_
    extends CityAdapter
{

    private Context context_;

    private CityAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static CityAdapter_ getInstance_(Context context) {
        return new CityAdapter_(context);
    }

    private void init_() {
        mContext = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
