//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.appassit.adapter;

import android.content.Context;

public final class FutureWeatherAdapter_
    extends FutureWeatherAdapter
{

    private Context context_;

    private FutureWeatherAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static FutureWeatherAdapter_ getInstance_(Context context) {
        return new FutureWeatherAdapter_(context);
    }

    private void init_() {
        mContext = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
