//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.appassit.service;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class WeatherUpdateService_
    extends WeatherUpdateService
{

    private Handler handler_ = new Handler(Looper.getMainLooper());

    public static WeatherUpdateService_.IntentBuilder_ intent(Context context) {
        return new WeatherUpdateService_.IntentBuilder_(context);
    }

    @Override
    public void updateWeather() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                WeatherUpdateService_.super.updateWeather();
            }

        }
        );
    }

    @Override
    public void updateTime() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                WeatherUpdateService_.super.updateTime();
            }

        }
        );
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<WeatherUpdateService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, WeatherUpdateService_.class);
        }

    }

}
