//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.appassit.fragments;

import android.R.anim;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.widget.SwipeRefreshLayout;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.view.animation.AnimationUtils;
import android.widget.TextView;
import com.appassit.R.layout;
import com.appassit.adapter.FutureWeatherAdapter_;
import com.appassit.widget.jazzylistview.JazzyListView;
import com.appassit.widget.jazzyviewpager.JazzyViewPager;
import org.androidannotations.api.BackgroundExecutor;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class ToadyFragment_
    extends com.appassit.fragments.ToadyFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.fragment_today_weather, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        fadeIn = AnimationUtils.loadAnimation(getActivity(), anim.fade_in);
        mFutureWeatherAdapter = FutureWeatherAdapter_.getInstance_(getActivity());
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ToadyFragment_.FragmentBuilder_ builder() {
        return new ToadyFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mViewPager = ((JazzyViewPager) hasViews.findViewById(com.appassit.R.id.jazzy_pager));
        tvWeather = ((TextView) hasViews.findViewById(com.appassit.R.id.tv_weather));
        mFutureWeatherListView = ((JazzyListView) hasViews.findViewById(com.appassit.R.id.lv_weather));
        mSwipeRefreshLayout = ((SwipeRefreshLayout) hasViews.findViewById(com.appassit.R.id.swipe_layout));
        tvTemp = ((TextView) hasViews.findViewById(com.appassit.R.id.tv_temp));
        tvCity = ((TextView) hasViews.findViewById(com.appassit.R.id.tv_city));
        initFragment();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  1000 :
                ToadyFragment_.this.onResult(resultCode);
                break;
        }
    }

    @Override
    public void getDataFromDB() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ToadyFragment_.super.getDataFromDB();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void getAllWeather() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ToadyFragment_.super.getAllWeather();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    @Override
    public void inserData() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("", 0, "") {


            @Override
            public void execute() {
                try {
                    ToadyFragment_.super.inserData();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<ToadyFragment_.FragmentBuilder_, com.appassit.fragments.ToadyFragment>
    {


        @Override
        public com.appassit.fragments.ToadyFragment build() {
            ToadyFragment_ fragment_ = new ToadyFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
